
<div class="row panel panel-cuestionario panel-indice sombrear_cuadros">
    <div class="col-xs-6 col-sm-2"><a href="<?php echo Mage::getBaseUrl() ?>/elegir-mi-electrodomestico/lavadoras">Lavadoras</a></div>
    <div class="col-xs-6 col-sm-2"><a href="<?php echo Mage::getBaseUrl() ?>/elegir-mi-electrodomestico/frigorificos">Frigor&iacute;ficos</a></div>
    <div class="col-xs-6 col-sm-2"><a href="<?php echo Mage::getBaseUrl() ?>/elegir-mi-electrodomestico/lavavajillas">Lavavajillas</a></div>
    <div class="col-xs-6 col-sm-2"><a href="<?php echo Mage::getBaseUrl() ?>/elegir-mi-electrodomestico/Secadoras">Secadoras</a></div>
</div>