<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<div class="panel panel-primary sombrear_cuadros panel-cuestionario">
    <div class="panel-heading">Contesta a las siguientes preguntas y nosotros te daremos la mejor opci&oacute;n.</div>
    <div class="panel-body">
        <div id="pregunta-1" class="row-fluid">
            <div class="span6">
                <div class="questioncontent">
                    <p class="lead"> COMO QUIERES VER EL LAVAVAJILLAS EN TU COCINA? </p>
                    <div class="radio">
                        <label>
                            <input type="radio" name="vista" id="vista1" value="1" checked>
                            <p>No quiero verlo, quiero integrarlo en los muebles</p>
                        </label>
                     </div>
                     <div class="radio">
                        <label>
                          <input type="radio" name="vista" id="vista2" value="2">
                          <p>Lo quiero de libre instalaci&oacute;n ya que se tiene que ver</p>
                        </label>
                     </div>
                    <input type="button" value="Siguiente" class="btn btn-primary" onclick="siguientePregunta('pregunta-1', 'pregunta-2'), deshabilitarOpciones()" />
                </div>
            </div>
            <div class="span3">
                <img src="<?php echo $this->getSkinUrl('images/electrodomesticos/familia.png') ?>" width="300px" class="qimage "/>
            </div>
        </div>

        <div id="pregunta-2" class="row-fluid">
            <div class="span6">
                <div class="questioncontent">
                    <p class="lead"> QUE ANCHO TENGO DISPONIBLE?</p>
                    <div class="radio">
                        <label>
                          <input type="radio" name="ancho" id="ancho1" value="1" checked>
                          <p>60 cm (Medida standard)</p>
                        </label>
                     </div>
                     <div class="radio">
                        <label>
                          <input type="radio" name="ancho" id="ancho2" value="2">
                          <p>45 cm (Lavavajillas estrechos)</p>
                        </label>
                     </div>
                     <div class="radio">
                        <label>
                          <input type="radio" name="ancho" id="ancho3" value="3">
                          <p>Otras medidas</p>
                        </label>
                     </div>
                    <input type="button" value="Anterior" class="btn btn-primary" onclick="siguientePregunta('pregunta-2', 'pregunta-1')" />
                    <input type="button" value="Siguiente" class="btn btn-primary" onclick="siguientePregunta('pregunta-2', 'pregunta-3')" />
                </div>
            </div>
            <div class="span3">
                <img src="<?php echo $this->getSkinUrl('images/electrodomesticos/fresa.jpg') ?>" width="300px" class="qimage "/>
            </div>
        </div>


        <div id="pregunta-3" class="row-fluid">
            <div class="span6">
                <div class="questioncontent">
                    <p class="lead"> DE QUE COLOR QUIERES TU LAVAVAJILLAS? </p>
                    <div class="radio">
                        <label>
                          <input type="radio" name="diseno" id="diseno1" value="1">
                          <p>Blanco</p>
                        </label>
                     </div>
                     <div class="radio">
                        <label>
                          <input type="radio" name="diseno" id="diseno2" value="2">
                          <p>Acero inoxidable</p>
                        </label>
                     </div>
                     <div class="radio">
                        <label>
                          <input type="radio" name="diseno" id="diseno3" value="3">
                          <p>Otros colores</p>
                        </label>
                     </div>
                     <div class="radio">
                        <label>
                          <input type="radio" name="diseno" id="diseno4" value="4" checked>
                          <p>Sin color, ir&aacute; integrado en los muebles</p>
                        </label>
                     </div>
                    <input type="button" value="Anterior" class="btn btn-primary" onclick="siguientePregunta('pregunta-3', 'pregunta-2')" />
                    <input type="button" value="Siguiente" class="btn btn-primary" onclick="siguientePregunta('pregunta-3', 'pregunta-4')" />
                </div>
            </div>
            <div class="span3">
                <img src="<?php echo $this->getSkinUrl('images/electrodomesticos/diseno_frigo.jpg') ?>" width="300px" class="qimage "/>
            </div>
        </div>

        <div id="pregunta-4" class="row-fluid">
            <div class="span6">
                <div class="questioncontent">
                    <p class="lead"> A LA HORA DE COMPRAR TU NUEVO LAVAVAJILLAS QUE VALORAS M&Aacute;S? </p>
                    <div class="radio">
                        <label>
                          <input type="radio" name="valor" id="valor1" value="1" checked>
                          <p>Quiero que consuma muy poca agua y energ&iacute;a aunque sea m&aacute;s caro</p>
                        </label>
                     </div>
                     <div class="radio">
                        <label>
                          <input type="radio" name="valor" id="valor2" value="2">
                          <p>Quiero que consuma muy poca agua y energ&iacute;a pero el precio es muy importante</p>
                        </label>
                     </div>
                    <div class="radio">
                        <label>
                          <input type="radio" name="valor" id="valor3" value="3">
                          <p>No me importa que consuma m&aacute;s agua y energ&iacute;a si me ahorro m&aacute;s dinero</p>
                        </label>
                     </div>
                    <input type="button" value="Anterior" class="btn btn-primary" onclick="siguientePregunta('pregunta-4', 'pregunta-3')" />
                    <button class="btn btn-primary" onclick="getRespuestas()"><span class="glyphicon glyphicon-play"></span>Ver resultados</button>
                </div>
            </div>
            <div class="span3">
                <img src="<?php echo $this->getSkinUrl('images/electrodomesticos/lugar.png') ?>" width="270px" class="qimage "/>
            </div>
        </div>
    </div>
</div>





<?php //LLAMAMOS AL METODO SAVE DEL CONTROLADOR DE LA EXTENSION PASANDOLE VIA AJAX LAS RESPUESTAS ?>
<script type="text/javascript">
    function getRespuestas(){
        var vista = jQuery("input[name='vista']:checked").val();
        var ancho = jQuery("input[name='ancho']:checked").val();
        var diseno = jQuery("input[name='diseno']:checked").val();
        var eco = jQuery("input[name='valor']:checked").val();
        
        var propiedades = {"vista": vista, "ancho": ancho, "diseno": diseno, "eco": eco}; //pasamos todo via json
        
        jQuery('#divResultado').css("display", "none");

        jQuery('#loading').html('<img src="http://www.gifmania.com/Gif-Animados-Web/Imagenes-Rotulos-Webs/Rotulos-Cargando/Circulo-Carga-62157.gif" class="loading" />  ');
        jQuery.ajax({
           url: "<?php echo Mage::getUrl('elegir-mi-electrodomestico/lavavajillas/guardar') ?>",
           type: "POST",
           data: propiedades,
           success: function(data){
               jQuery('#loading').hide();
               jQuery('#divResultado').slideDown('slow');
               if (data == '1'){
                   vaciarCampos();
                   jQuery('.no-results').html('Lamentamos informarle que no hemos podido conseguir un lavavajillas que se adapte a sus necesidades, si lo prefiere puede volver a realizar el test');
               }
               else{
                    var resul = JSON.parse(data);
                    vaciarCampos();
                    for (var i=0; i <= resul.length; i++){
                        jQuery('#res' + i).html('<a href="'+ resul[i].url +'"><img src="' + resul[i].image + '" /></a><p class="lead">' + resul[i].nombre + '</p>');
                        //PARA ELEGIR
                        //precio = resul[i].precio
                        //descripcion_corta = resul[i].desc_corta
                    }
               }
           }
        });
    }
    
    function deshabilitarOpciones(){
        if (jQuery("input[name='vista']:checked").val() == '1'){
            document.getElementById('diseno1').disabled = true;
            document.getElementById('diseno2').disabled = true;
            document.getElementById('diseno3').disabled = true;
        }
        else{
            document.getElementById('diseno1').disabled = false;
            document.getElementById('diseno2').disabled = false;
            document.getElementById('diseno3').disabled = false;
        }
    }
    
</script>