<div id="divResultado">
    <div class="panel panel-primary sombrear_cuadros panel-cuestionario">
        <div class="panel-heading">Nuestras opciones</div>
            <div class="panel-body">
                <div class="col-md-3" id="res0"></div>
                <div class="col-md-3" id="res1"></div>
                <div class="col-md-3" id="res2"></div>
            </div>
        <p class="no-results"></p>
    </div>
</div>